// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeaV5czPOk5OYmqaLHuzGdZNBgXUU10aM',
    appId: '1:349783052890:web:bc355f569f6e77b4753e63',
    messagingSenderId: '349783052890',
    projectId: 'app-ricette-a59a6',
    authDomain: 'app-ricette-a59a6.firebaseapp.com',
    storageBucket: 'app-ricette-a59a6.firebasestorage.app',
    measurementId: 'G-HF07M72CWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUO4VKflBTGfO1yytsrXxypto7NlU3nRI',
    appId: '1:349783052890:android:c5554b8c075b1ffa753e63',
    messagingSenderId: '349783052890',
    projectId: 'app-ricette-a59a6',
    storageBucket: 'app-ricette-a59a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2_24nAvYgUqUcMRLWP4ShziAKdNZJ0ss',
    appId: '1:349783052890:ios:b10113a2e9a4cdfb753e63',
    messagingSenderId: '349783052890',
    projectId: 'app-ricette-a59a6',
    storageBucket: 'app-ricette-a59a6.firebasestorage.app',
    iosClientId: '349783052890-onde248tth0u5q208khan2v6dkfld9u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appRicette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2_24nAvYgUqUcMRLWP4ShziAKdNZJ0ss',
    appId: '1:349783052890:ios:b10113a2e9a4cdfb753e63',
    messagingSenderId: '349783052890',
    projectId: 'app-ricette-a59a6',
    storageBucket: 'app-ricette-a59a6.firebasestorage.app',
    iosClientId: '349783052890-onde248tth0u5q208khan2v6dkfld9u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appRicette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeaV5czPOk5OYmqaLHuzGdZNBgXUU10aM',
    appId: '1:349783052890:web:acd77551e8edaf11753e63',
    messagingSenderId: '349783052890',
    projectId: 'app-ricette-a59a6',
    authDomain: 'app-ricette-a59a6.firebaseapp.com',
    storageBucket: 'app-ricette-a59a6.firebasestorage.app',
    measurementId: 'G-6GWFHSWTYC',
  );
}
